using System;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace webapp.Models
{
    public class BaseEntity
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }

        public int Id { get; set; }

        [BsonDateTimeOptions(Kind = DateTimeKind.Local)]
        public DateTime UpdatedOn { get; set; } = DateTime.Now;



    }

}
